development:
   encoding: utf8
   reconnect: false
   adapter: mysql2
   database: ruby_devlopment
   username: root
   password:
   host: localhost

test:
   encoding: utf8
   reconnect: false
   adapter: mysql2
   database: ruby_test
   username: root
   password:
   host: localhost

production:
   encoding: utf8
   reconnect: false
   adapter: mysql2
   database: library_production
   username: root
   password: [password]
   host: localhost
