development:
   encoding: utf8
   reconnect: false
   adapter: mysql2
   pool: 5
   database: ruby_devlopment
   username: root
   password:
   host: localhost

test:
   encoding: utf8
   reconnect: false
   adapter: mysql2
   pool: 5
   database: ruby_test
   username: root
   password:
   host: localhost

production:
   encoding: utf8
   reconnect: true
   adapter: mysql2
   pool: 5
   database: <%= ENV['DB_NAME'] %>
   username: <%= ENV['DB_USER'] %>
   password: <%= ENV['DB_PASS'] %>
   host: <%= ENV['DB_HOST'] %>
