# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3721ebfb1fd71bd2342369074e5dc8a5f0465dca338a5ed8c3e277ff1848e6132c78f33829ac978afd0a711c39ce2aa33d1f4838dd4e09b5e666ccdfa91265a

test:
  secret_key_base: 9313364da58f589fc1cfd18b88860361f598bc875385060a71b24e2bb491019023de301476fba3fd226f9c92ad328286318eb35c53ad3ccaeb832073c1de83e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
